# ============================
# Server
# ============================
server.port=8080

# ============================
# Database - PostgreSQL + pgvector
# ============================
spring.datasource.url=jdbc:postgresql://ep-billowing-rain-aiflwpku.c-4.us-east-1.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_a1kwZOzKXPE2
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


rag.data.raw-path=rag-data/raw-files
rag.data.processed-path=rag-data/processed

jwt.secret=${JWT_SECRET:ThisIsAVerySecretKeyForDecisionDetective2024MakeItLong}
jwt.expiration.ms=86400000


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

gemini.api.key=AIzaSyBQJjVuZiNXNRRpKgc5UHnOp_8QJHg60Zw
gemini.model.embedding=gemini-embedding-001
gemini.embedding.dimension=3072
spring.jackson.serialization.fail-on-empty-beans=false
gemini.model.chat=gemini-2.5-flash